export function buildConversationSystemPrompt({
  characters,
  room,
  roomEffect,
  transcriptTurnCount,
  relationshipGuidance,
}) {
  return [
    'You are writing a short conversation for a goofy apartment game.',
    'You may include occasional action beats inside square brackets like [glances away].',
    'Return JSON only. No markdown fences, no explanation.',
    `Return an object with one key: "turns". "turns" must be an array of exactly ${transcriptTurnCount} items.`,
    'Each turn must be an object with "speakerId" and "text".',
    'The speakers must alternate every turn, beginning with the provided startingSpeakerId.',
    'Each text value must stay under 35 words and sound like actual speech.',
    'Keep it simple. No fancy writing. No speeches. No deep monologues.',
    'The scene should feel funny, weird, petty, playful, or a little stupid in a good way.',
    'Let the characters joke, misunderstand things, exaggerate tiny problems, and say mildly ridiculous stuff when it fits.',
    'Each line still has to match the speaker. Their personality should shape what they notice, what they want, and how they talk.',
    'Do not make all three characters sound the same.',
    'Do not introduce people outside the house cast.',
    'Keep the relationship history alive. They know each other, and that should show.',
    `Room context: ${room.name}. Mood: ${room.mood}. ${room.promptNote}`,
    `Room effect: ${roomEffect.label}. ${roomEffect.summary}`,
    'Room effect rules:',
    ...roomEffect.promptRules.map((rule) => `- ${rule}`),
    `Relationship context: ${relationshipGuidance}`,
    'Character briefs:',
    ...characters.map(
      (character) => `- ${character.id} (${character.name}, ${character.role}): ${character.personality}`,
    ),
  ].join('\n');
}

export function buildConversationTurnSystemPrompt({
  characters,
  room,
  roomEffect,
  transcriptTurnCount,
  relationshipGuidance,
  turnNumber,
  expectedSpeakerId,
  historyLines,
}) {
  return [
    'You are writing exactly one turn of dialogue for a goofy apartment game.',
    'You may include occasional action beats inside square brackets like [glances away].',
    'Return JSON only. No markdown fences, no explanation.',
    'Return an object with exactly two keys: "speakerId" and "text".',
    `This is turn ${turnNumber} of ${transcriptTurnCount}.`,
    `The speaker for this turn must be "${expectedSpeakerId}".`,
    'The text must stay under 35 words and sound like actual speech.',
    'Keep it simple. No fancy writing. No speeches. No deep monologues.',
    'The scene should feel funny, weird, petty, playful, or a little stupid in a good way.',
    'Let the line fit the speaker. Their personality should shape the joke, the annoyance, the dodge, or the overreaction.',
    'Do not make everybody sound the same.',
    'Do not introduce people outside the house cast.',
    'Keep the relationship history alive.',
    `Room context: ${room.name}. Mood: ${room.mood}. ${room.promptNote}`,
    `Room effect: ${roomEffect.label}. ${roomEffect.summary}`,
    'Room effect rules:',
    ...roomEffect.promptRules.map((rule) => `- ${rule}`),
    `Relationship context: ${relationshipGuidance}`,
    'Character briefs:',
    ...characters.map(
      (character) => `- ${character.id} (${character.name}, ${character.role}): ${character.personality}`,
    ),
    'Prior turns:',
    historyLines,
  ].join('\n');
}
